apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-dance-templates
  description: A collection of RHDH templates for Project Dance
spec:
  type: url
  targets:
     - https://{{ gitlab_host }}/{{ gitlab_group }}/trusted-application-pipeline-templates/blob/main/scaffolder-templates/quarkus-stssc-template/template.yaml
     - https://{{ gitlab_host }}/{{ gitlab_group }}/trusted-application-pipeline-templates/blob/main/scaffolder-templates/quarkus-stssc-jenkins-template/template.yaml
